### PR TITLE
Ldap keystone

### PR DESCRIPTION
**Pull request by hicham-a**

### CODE REVIEW

**Comment by brunopereira81** [comment]
In some scripts that are now part of Trinity we can see:

_# IBM(c) 2014 EPL license http://www.eclipse.org/legal/epl-v10.html_

The license that we are using for Trinity seems to be GPL3, which seems incompatible with EPL, so those files cannot be packed or distributed with Trinity.

Files affected:

 controller/rootimg/install/postscripts/configeth
 controller/rootimg/install/postscripts/cv_configeth_noip

Can you have a look please?

**Comment by hansthen** [comment]
That's incorrect. GPL3 is a different license from the EPL. To conclude from that that we cannot pack or distribute those files with Trinity looks like a legal misunderstanding of either or both of the two licenses.

**Comment by brunopereira81** [comment]
Fair enough, but to be clear it was never an assumption that GPL3 and EPL are the same licenses.

**Comment by brunopereira81** [comment]
So, having a quick chat with someone who actually understands these things it came out that, yes, you can pack and distribute EPL files with your GPLv3 code, as long as the code released within the project under GPLv3 is 100% created by you.

Any other code that is released as part of, or used by Trinity under GPLv3 that its not authored by you cannot be mixed with EPL for as long as no explicit permission is given by the authors of that code following section 7 of the GPLv3 license.

**Pull request merged**
